name: autocnet
channels:
  - conda-forge
  - usgs-astrogeology
  - menpo
dependencies:
  - python >= 3
  - coveralls
  - csmapi
  - cyvlfeat
  - geoalchemy2
  - geopandas
  - imageio
  - knoten
  - ncurses
  - networkx
  - numpy
  - opencv
  - pillow
  - pip:
    - redis
  - plio >= 1.1.0
  - plurmy
  - pyproj
  - pytest
  - pytest-cov
  - scikit-image
  - scipy
  - shapely
  - sqlalchemy
  - vlfeat