channels:
  - conda-forge
  - usgs-astrogeology
  - menpo

dependencies:
  - python >= 3
  - coveralls
  - csmapi
  - cyvlfeat
  - dill
  - geoalchemy2
  - geopandas
  - hoggorm
  - imageio
  - ipykernel
  - jupyter
  - knoten
  - ncurses
  - networkx
  - numpy
  - opencv <= 3.5
  - pillow
  - pip
  - plio >= 1.1.0
  - plurmy
  - psycopg2
  - proj >= 7.0.0
  - pyproj
  - pytest
  - pytest-cov
  - pysis
  - pvl < 1.0
  - richdem
  - scikit-image
  - scikit-learn
  - scipy<=1.2.1
  - shapely
  - sqlalchemy < 1.4
  - sqlalchemy-utils=0.36.7
  - redis-py
  - usgscsm
  - vlfeat