name: autocnet
channels:
  - usgs-astrogeology
  - conda-forge
  - jlaura
  - menpo
dependencies:
  - python=3
  - cython
  - matplotlib
  - dill
  - jupyter
  - networkx
  - numexpr
  - pandas
  - geopandas
  - shapely
  - pyyaml
  - scipy
  - sqlalchemy
  - plio
  - pip:
    - pillow
    - pvl
    - libpysal
    - protobuf
