package:
  name: autocnet
  version: 0.1.0

source:
  git_rev: v0.1.0
  git_url: https://github.com/USGS-Astrogeology/autocnet.git

build:
  number: 0

requirements:
  build:
    - python
    - opencv3 3.0.0
    - numpy
    - scipy
    - pillow
    - pandas
    - networkx
    - sqlalchemy
    - numexpr
    - cython
    - dill
    - pyyaml
    - gdal
    - h5py
  run:
    - python
    - opencv3 3.0.0
    - numpy
    - scipy
    - pillow
    - pandas
    - networkx
    - sqlalchemy
    - numexpr
    - cython
    - dill
    - pyyaml
    - gdal
    - h5py

about:
  home: http://autocnet.readthedocs.org
  license: Public Domain
  summary: Autocnet is a library top
