package:
  name: autocnet
  version: 0.2.2
  
channels:
  - conda-forge
  - menpo
  - usgs-astrogeology
  
source:
   git_url: https://github.com/USGS-Astrogeology/autocnet.git
   git_rev: dev

requirements:
  build:
    - python=3
    - vlfeat
    - cyvlfeat
    - pillow
    - scipy
    - networkx
    - numexpr
    - cython
    - matplotlib
    - geopandas
    - opencv
    - numpy
    - plio
    - gdal
  run:
    - python=3
    - vlfeat
    - cyvlfeat
    - pillow
    - scipy
    - networkx
    - numexpr
    - cython
    - matplotlib
    - geopandas
    - opencv
    - numpy
    - plio
    - gdal
    - scikit-image

test:
  imports:
    - autocnet
    - autocnet.graph.network
